# 50 practice questions on Numpy

## File: N-1_Numpy_Intro_Dim.pdf (Introduction, Dimensions & 
Array Creation)
1. How do you create a 1D NumPy array with values [5, 10, 15, 20, 25]? 
2. Write the code to create a 1D array of numbers from 0 to 9 using the np.arange() 
function. 
3. How do you construct a 2D array (matrix) that has exactly 2 rows and 4 columns? 
4. Write a command to create a 3D array of shape (2, 2, 3) filled with random integers 
between 1 and 20. 
5. Write the NumPy code required to create a 2x3 array completely filled with zeros. 
6. How do you create a 3x4 array of ones and explicitly set the data type to integer? 
7. Write code to create a 2x2 array that is entirely filled with the number 9. 
8. How can you generate 5 evenly spaced numbers between 0 and 2 using np.linspace()? 
9. Write the code to generate a 4x4 identity matrix. 
10. Given an existing array b = [[1, 2, 3], [4, 5, 6]], how do you create a new array of zeros 
with the exact same shape as b? 

In [1]:
# 1. How do you create a 1D NumPy array with values [5, 10, 15, 20, 25]? 
import numpy as np
arr=np.array([5,10,15,20,25])
print(arr)

[ 5 10 15 20 25]


In [2]:
# 2. Write the code to create a 1D array of numbers from 0 to 9 using the np.arange() 
# function.

arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# 3. How do you construct a 2D array (matrix) that has exactly 2 rows and 4 columns? 

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [4]:
#4. Write a command to create a 3D array of shape (2, 2, 3) filled with random integers 
#between 1 and 20.
# 
arr=np.random.randint(1,21,size=(2,2,3))
print(arr) 

[[[18 14 15]
  [ 6  4 18]]

 [[ 2  4 19]
  [ 6 10 19]]]


In [5]:
#5. Write the NumPy code required to create a 2x3 array completely filled with zeros. 
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#6. How do you create a 3x4 array of ones and explicitly set the data type to integer? 
arr=np.ones((3,4),dtype=int)
print(arr)
print(arr.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64


In [7]:
#7. Write code to create a 2x2 array that is entirely filled with the number 9. 
arr=np.full((2,2),9)
print(arr)

[[9 9]
 [9 9]]


In [8]:
#8. How can you generate 5 evenly spaced numbers between 0 and 2 using np.linspace()? 
arr=np.linspace(0,2,5)
print(arr)

[0.  0.5 1.  1.5 2. ]


In [9]:
#9. Write the code to generate a 4x4 identity matrix. 
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
#10. Given an existing array b = [[1, 2, 3], [4, 5, 6]], how do you create a new array of zeros 
#with the exact same shape as b? 

b=np.array([[1,2,3],[4,5,6]])
a=np.zeros_like(b)
print(a)

[[0 0 0]
 [0 0 0]]


## File: N-2_Indexing_Slicing.pdf (Indexing, Slicing & Boolean Indexing)

In [11]:
# 11. Given the array arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90]), how do you access 
# the first and last elements?

arr=np.array([10,20,30,40,50,60,70,80,90])
print(arr[[0,-1]])

[10 90]


In [12]:
#12. How do you completely reverse a 1D array in NumPy using slicing? 
arr=np.arange(11)
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1  0]


In [13]:
#13. Given the 2D array arr = [[11, 12, 13], [21, 22, 23], [31, 32, 33]], write the code to 
#extract the element located in the 2nd row and 3rd column

arr=np.array([[11,12,13],[21,22,23],[31,32,33]])
print(arr[1,2])

23


In [14]:
#14. From a 2D array, how do you use slicing to extract only the first column? 
arr=np.array([[11,12,13],[21,22,23],[31,32,33]])
print(arr[:,0])

[11 21 31]


In [15]:
# 15. Write code to replace the value at position (1, 1) in a 2D array with the number 999. 
arr = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
arr[1,1] = 999
print(arr)

[[ 11  12  13]
 [ 21 999  23]
 [ 31  32  33]]


In [16]:
#16. Given arr = np.array([5, 10, 15, 20, 25, 30, 35, 40]), write a slice to extract elements 
#from index 2 until the end of the array.

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
print(arr[2:])

[15 20 25 30 35 40]


In [17]:
#17. How do you extract all values greater than 20 from a 1D array using boolean indexing? 
print(arr[arr>20])

[25 30 35 40]


In [18]:
#18. Write a NumPy command to extract only the even numbers from a given array. 
print(arr[arr%2==0])

[10 20 30 40]


In [19]:
#19. Given the array [100, 200, 300, 400, 500, 600], how do you select elements at specific 
#index positions [0, 2, 4] using fancy indexing? 
arr=np.array([100,200,300,400,500,600])
print(arr[[0,2,4]])


[100 300 500]


In [20]:
#20. Given scores = np.array([56, 72, 89, 45, 68, 91, 77]), write the code to replace all scores 
#that are below 50 with a value of 0

scores=np.array([56, 72, 89, 45, 68, 91, 77])
scores[scores<50]=0
print(scores)

[56 72 89  0 68 91 77]


## File: N-3_dtype_shape_reshape.pdf (Data Types, Shape & Reshaping)

In [21]:
#21. What properties do you use to check the data type and the shape of a NumPy array? 
print(arr.dtype)
print(arr.shape)

int64
(6,)


In [22]:
#22. Write code to convert a float array [2.9, 4.1, 6.8, 9.5] into integers using astype(). 
f_arr=np.array([2.9,4.1,6.8,9.5])
i_arr=f_arr.astype(int)
print(i_arr)

[2 4 6 9]


In [23]:
#23. How do you reshape a 1D array of size 12 into a 2D array with the shape (3, 4)? 
arr=np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
#24. Write code to reshape a 1D array of 12 elements into a 3D array of shape (2, 2, 3). 
arr=np.arange(12).reshape(2, 2, 3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [25]:
#25. How do you instruct NumPy to automatically calculate an unknown dimension when 
#reshaping an array?
arr=np.arange(12).reshape(2, -1)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [26]:
#26. What is the fundamental difference between flattening an array using flatten() versus 
#using ravel()? 
# The fundamental difference between flatten() and ravel() is that flatten() returns a copy of the array, while ravel() returns a view of the original array whenever possible. This means that changes made to the array returned by flatten() will not affect the original array, whereas changes made to the array returned by ravel() may affect the original array if it is a view.
arr=np.array([[1,2,3],[4,5,6]])
flattened_arr = arr.flatten()
print(flattened_arr)

raveled_arr = arr.ravel()
print(raveled_arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [27]:
#27. How do you add a new axis to convert a 1D array [1, 2, 3, 4] into a column vector of 
#shape (4, 1) using np.expand_dims()? 
arr=np.array([1,2,3,4])
new_arr=np.expand_dims(arr,axis=1)
print(new_arr)

[[1]
 [2]
 [3]
 [4]]


In [28]:
#28. Write code to remove all extra dimensions of size 1 from an array of shape (1, 5, 1) 
#using the np.squeeze() function. 
arr=np.array([[[1],[2],[3],[4],[5]]])
print("Original shape:", arr.shape)
squeezed_arr=np.squeeze(arr)
print("Squeezed shape:", squeezed_arr.shape)

Original shape: (1, 5, 1)
Squeezed shape: (5,)


In [29]:
#29. How do you swap the axes (transpose) of a 2D array? 
arr=np.array([[1,2,3],[4,5,6]])
transposed_arr=arr.T
print(transposed_arr)


[[1 4]
 [2 5]
 [3 6]]


In [30]:
#30. Write code to reshape a dataset of 100 grayscale images of shape (100, 28, 28) into a 
#flattened 2D array of shape (100, 784).
images=np.random.rand(100,28,28)
flattened_images=images.reshape(100, -1)
print(flattened_images.shape)

(100, 784)


## File: N-4_Iterating.pdf (Iterating Arrays)


In [31]:
#31. Write a standard Python for loop to iterate through all elements of a basic 1D array. 
arr=np.array([10,20,30,40,50])
for i in arr:
    print(i)

10
20
30
40
50


In [32]:
#32. How do you iterate through a 2D array element-by-element using nested loops? 
arr=np.arange(1,10).reshape(3,3)
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [33]:
#33. Write the code to iterate through every element of a 3D array efficiently using 
#np.nditer()
arr=np.random.randint(0,10,(2,2,3))
for x in np.nditer(arr):
    print(x)

3
9
8
2
5
4
4
1
8
3
5
0


In [34]:
#34. How do you iterate through an array while keeping track of the exact index of each 
#element using np.ndenumerate()?

arr=np.array([[11,12,13],[21,22,23],[31,32,33]])
for index,value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 11
Index: (0, 1), Value: 12
Index: (0, 2), Value: 13
Index: (1, 0), Value: 21
Index: (1, 1), Value: 22
Index: (1, 2), Value: 23
Index: (2, 0), Value: 31
Index: (2, 1), Value: 32
Index: (2, 2), Value: 33


In [35]:
#35. Write code to modify a 2D array in-place during iteration by replacing all elements at 
#even row indices with 0.

arr = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
for i in range(arr.shape[0]):
    if i % 2 == 0:  
        arr[i, :] = 0  
print(arr)

[[ 0  0  0]
 [21 22 23]
 [ 0  0  0]]


In [36]:
#36. Given two arrays a = np.array([1, 2, 3]) and b = np.array([[10], [20], [30]]), write code 
#to print their element-wise sum using broadcasting with np.nditer([a, b]).
a=np.array([1,2,3])
b=np.array([[10],[20],[30]])
for x,y in np.nditer([a,b]):
    print(x+y)

11
12
13
21
22
23
31
32
33


In [37]:
#37. How do you flatten an N-dimensional array first so that you can iterate over it as a 
#standard 1D array in a single loop? 
arr=np.random.randint(0, 10, (2, 2, 3))
for x in arr.flatten():
    print(x)

1
5
1
7
7
6
8
9
6
1
0
8


## File: N-5_join_stack_split.pdf (Joining, Stacking & Splitting Arrays)

In [38]:
#38. Given two 1D arrays [1, 2, 3] and [4, 5, 6], how do you join them into a single 1D array 
#using np.concatenate()? 
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [39]:
# 39. Write code to stack two 1D arrays horizontally using np.hstack(). 
c=np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [40]:
#40. How do you join two 2D arrays row-wise (vertically) using np.vstack()? 
c=np.vstack((a,b))  
print(c)

[[1 2 3]
 [4 5 6]]


In [41]:
#41. Write code to take two 1D arrays and combine them into a 2D column matrix using 
# np.column_stack(). 
c=np.column_stack((a,b))
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
# 42. How do you stack two (2, 2) arrays along their depth (the 3rd axis) using np.dstack()? 
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dstack((a,b))
print(c)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [43]:
#43. Write code to divide a 1D array [10, 20, 30, 40, 50, 60, 70, 80] into 4 strictly equal parts 
# using np.split().
arr=np.array([10,20,30,40,50,60,70,80])
split_arr=np.split(arr,4)
print(split_arr)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]


In [44]:
#44. What function do you use if you want to split an array into unequal parts without 
#triggering an error?
arr=np.array([10,20,30,40,50,60,70,80])
split_arr=np.array_split(arr,3)
print(split_arr)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80])]


In [45]:
#45. How do you horizontally split a 2D array into 2 equal left-and-right halves using 
# np.hsplit()?
arr=np.array([[1,2,3,4],[5,6,7,8]])
split_arr=np.hsplit(arr,2)
print(split_arr)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [46]:
#46. Write code to vertically split a 2D array into separate rows using np.vsplit(). 
v_split_arr=np.vsplit(arr,2)
print(v_split_arr)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [47]:
#47. Given a 2D array representing quarterly revenue for 3 years, write the code to split this 
#data into 4 parts, representing Q1, Q2, Q3, and Q4.
revenue_data = np.array([[100, 150, 200, 250],
                        [300, 350, 400, 450],
                        [500, 550, 600, 650]])
q1_data, q2_data, q3_data, q4_data = np.hsplit(revenue_data, 4)
print("Q1 Data:\n", q1_data)
print("Q2 Data:\n", q2_data)
print("Q3 Data:\n", q3_data)
print("Q4 Data:\n", q4_data)

Q1 Data:
 [[100]
 [300]
 [500]]
Q2 Data:
 [[150]
 [350]
 [550]]
Q3 Data:
 [[200]
 [400]
 [600]]
Q4 Data:
 [[250]
 [450]
 [650]]
