# Intro to numpy

In [ ]:
import numpy as np

# arr_0_d=np.array(12)
# print(arr_0_d)

# arr_1_d=np.array([1,2,3,4,5])
# print(arr_1_d)
# print(arr_1_d.ndim)

# arr_2_d=np.array([[1,2,3],[4,5,6],[7,8,9]])
# print(arr_2_d)
# print(arr_2_d.ndim)

# arr_3_d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
# print(arr_3_d)
# print(arr_3_d.ndim)

arr_0=np.zeros((2,3,4))
# print(arr_0)
# print(arr_0.ndim)


#ones() function is used to create an array filled with ones. It takes a tuple as an argument that specifies the shape of the array. For example, np.ones((2,3)) will create a 2x3 array filled with ones.
arr_1=np.ones((2,3))
# print(arr_1)

#full() function is used to create an array filled with a specified value. It takes two parameters: shape and fill_value. The shape parameter is a tuple that specifies the shape of the array, and the fill_value parameter is the value that will be used to fill the array.
arr_2=np.full((2,3),7)
# print(arr_2)


#arange() function is used to create an array with a range of values. It takes three parameters: start, stop, and step. The start parameter is the value at which the array starts, the stop parameter is the value at which the array ends (exclusive), and the step parameter is the increment between each value in the array.
arr=np.arange(1,11,2)
print(arr)

#
arr=np.arange(11)
print(arr)

# linspace() function is used to create an array with a specified number of evenly spaced values between a given start and stop value. It takes three parameters: start, stop, and num. The start parameter is the value at which the array starts, the stop parameter is the value at which the array ends (inclusive), and the num parameter is the number of values to generate in the array.
arr=np.linspace(1,10,5)
print(arr)





[1 3 5 7 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1.    3.25  5.5   7.75 10.  ]





Practice Questions:-


Q-1: Create a 1D array with values [5,10,15,20,25].

->Print the array.

->Print its dimension and shape.


Q-2: Create a 1D array of numbers from 0 to 9.

->Verify that its 1D.

->Print its shape.


Q-3: Create 2D array(matrix) with 2 rows and 4 columns using your own numbers.

->Print the array.

->Print its ndim and shape.


Q-4: Create a 2D array (3*3) filled with numbers 1 to 9.

->Print the array.

->Verify its Dimension and Shape.


Q-5: Create 3D array with 2 blocks, each block having 3 rows and 2 columns.

->Print the array.

->Print its shape and dimensions.

Q-6 Create a 3D array with random integers between 1 and 20. Shape should be(2,2,3).

->Print the array.

->Print its dimension and shape.

Q-7 Create 4D array with shape(1,2,2,3).

->Print the array.

->Print its shape and dimensions.



In [12]:
#Q-1: Create a 1D array with values [5,10,15,20,25].

#->Print the array.

#->Print its dimension and shape.

arr=np.array([5,10,15,20,25])
print(arr)
print(arr.ndim)
print(arr.shape)

[ 5 10 15 20 25]
1
(5,)


In [13]:
#Q-2: Create a 1D array of numbers from 0 to 9.

#->Verify that its 1D.

#->Print its shape.

arr=np.arange(10)
print(arr.ndim)
print(arr.shape)

1
(10,)


In [14]:
#Q-3: Create 2D array(matrix) with 2 rows and 4 columns using your own numbers.

#->Print the array.

#->Print its ndim and shape.

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.ndim)
print(arr.shape)


[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [19]:
#Create a 2D array (3*3) filled with numbers 1 to 9.

#->Print the array.

#->Verify its Dimension and Shape.

arr=np.arange(1,10).reshape(3,3)
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [20]:

#Q-5: Create 3D array with 2 blocks, each block having 3 rows and 2 columns.

#->Print the array.

#->Print its shape and dimensions.

arr=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr)
print(arr.ndim)
print(arr.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [21]:
#Q-6 Create a 3D array with random integers between 1 and 20. Shape should be(2,2,3).

#->Print the array.

#->Print its dimension and shape.

arr=np.random.randint(1,21,size=(2,2,3))
print(arr)
print(arr.ndim)
print(arr.shape)

[[[13 18  1]
  [ 5  3 15]]

 [[14  6  2]
  [12  4 17]]]
3
(2, 2, 3)


In [23]:
#Q-7 Create 4D array with shape(1,2,2,3).

#->Print the array.

#->Print its shape and dimensions.

arr=np.random.randint(1,21,size=(1,2,2,3))
print(arr)
print(arr.ndim)
print(arr.shape)

[[[[ 7 19 14]
   [ 8 14 10]]

  [[ 2  9 13]
   [14  4 12]]]]
4
(1, 2, 2, 3)


----------------------------------------------------------------------------------------------------------

Practice Questions:


Q-1: Create a 2*3 array of zeros.Print dimension and shape.

Q-2: Create a 3*4 array of ones(int type).

Q-3: Create a 2*2 array filled with 9.

Q-4: Create an empty 2*3 array and print it.

Q-5: Create a 1D array of numbers from 10 to 50 with step=5 using arange.

Q-6: Create 5 evenly spaced numbers between 0 and 2 using linespace.

Q-7: Create a 4*4 identity matrix.

Q-8: Given array b=[[1,2,3],[4,5,6]],create zeros_like(b) and ones_like(b). 


----------------------------------------------------------------------------------------------------------

In [24]:
#Q-1: Create a 2*3 array of zeros.Print dimension and shape.

arr=np.zeros((2,3))
print(arr)
print(arr.ndim)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
2
(2, 3)


In [25]:
#Q-2: Create a 3*4 array of ones(int type).

arr=np.ones((3,4),dtype=int)
print(arr)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [26]:
#Q-3: Create a 2*2 array filled with 9.

arr=np.full((2,2),9)
print(arr)

[[9 9]
 [9 9]]


In [27]:
#Q-4: Create an empty 2*3 array and print it.
arr=np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#Q-5: Create a 1D array of numbers from 10 to 50 with step=5 using arange.

arr=np.arange(10,51,5)
print(arr)


[10 15 20 25 30 35 40 45 50]


In [30]:
#Q-6: Create 5 evenly spaced numbers between 0 and 2 using linespace.

arr=np.linspace(0,2,5)
print(arr)

[0.  0.5 1.  1.5 2. ]


In [31]:
#Q-7: Create a 4*4 identity matrix.

arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
#Q-8: Given array b=[[1,2,3],[4,5,6]],create zeros_like(b) and ones_like(b). 

arr=np.array([[1,2,3],[4,5,6]])
zeros_arr=np.zeros_like(arr)
ones_arr=np.ones_like(arr)
print(zeros_arr)
print(ones_arr)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
