# Practice questions:-


Q-1: Create a 1D NumPy array of size 10.

->Find its shape,ndim and size.


Q-2: Make a 2D array of shape(3,4) with values from 0 to 11.

->Print its shape,ndim and size.


Q-3: Convert a 1D array of size 12 into:

->shape(3,4)

->shape(2,2,3)

->shape(6,2)


Q-4: Use -1 in reshape to automatically calculate the missing dimension. Example reshape(3,4) into (2,-1)


Q-5: Create a 2D array of shape (3,3) and:

->Flatten it into 1D using flatten()

->Convert it into 1D using ravel() and change one element.

->Check whether original array changes or not.


Q-6 Take a 1D array [1,2,3,4]

->Convert it into shape(1,4) using np.newaxis

->Convert it into shape(4,1) using np.expand_dims


Q-7: Create an array of shape(1,5,1) and remove all extra dimensions using squeeze().


Q-8: Make a 2D array of shape(2,3) and print its transpose.

->Verify shape before and after transpose.


Q-9: Create a 3D array of shape (2,3,4) and use transpose() to swap axes.

->Try arr.transpose(1,0,2) and check new shape.


Q-10: Suppose you have 100 images stored in an array with shape(100,28,28) (100 grayscale images of 28*28).

->Reshape this into (100,784) (flatten each image into 1D of 784 pixels.)

->Then again reshape one image back to (28,28)


Q-11:You have a dataset with 1000 rows (samples) and 10 features->shape(1000,10).

(a) Find its ndim,size and shape.

(b) Reshape it into (10,1000) and observe the diffrence.

(c) Extract a single feature as a 1D vector (1000,).

(d) Extract a single feature as a column vector (1000,1).


Q-12 A grayscale image has shape(28,28).

(a)Flatten it into shape(28,28).

(b)Suppose you have 500 such images->shape(500,28,28).

->Reshape it into (500,784) for ML model input.

->Take one image from the dataset and reshape it back to (28,28).


Q-13:An RGB image has shape(64,64,3)->(height,width,channels).

(a)Reshape it into (4096,3) so each pixels RGB is a row.

(b) Suppose you have 100 images->shape(100,64,64,3).

->Reshape into (100,12288) for feeding into a neural network.

->Transpose a single image into (3,64,64) (channel-first format for PyTorch).


Q-14:A dataset has shape(10000,20) (10,000 samples,20 features).

(a)Reshape it into (100,100,20)->100 batches,each with 100 samples.

(b)Select one batch(100,20) and transpose it into (20,100).


Q-15:You have daily sensor data with shape(365,24)->365 days 24 hourly readings each day.

(a)Flatten it into (8760,).

(b)Add an extra dimension to make (365,24,1) for ML input.

(c)Use sequeeze to bring it back to (365,24).


Q-16: You have stock prices with shape(30,5)->30 days, 5 companies.

(a)Extract one company's stock price as a 1D array(30,).

(b)Convert the same into a column vector (30,1).

(c)Transpose the dataset to (5,30)->stocks*days.


Q-17:You have 1000 grayscale images of shape(1000,28,28).

(a)Reshape into (1000,28,28,1)->channel-last format(Tensorflow/Keras).

(b)Reshape into (1000,1,28,28)->channel-first format(PyTorch).

(c)Squeeze back into (1000,28,28).


Q-18:You have 200 senetences,each represented by 50 words,each word embedding of 100 dimensions.

->shape(200,50,100)

(a)Flatten each sentence into (200,5000) for a bag-of-word style model.

(b)Transpose it to (200,100,50) so embeddings come before word positions.

(c)Extract one sentence and reshape into (50,100)again.

In [1]:
# Q-1: Create a 1D NumPy array of size 10.
import numpy as np 
arr=np.arange(10)
#->Find its shape,ndim and size.

print(arr.shape)
print(arr.ndim)
print(arr.size)

(10,)
1
10


In [2]:
# Q-2: Make a 2D array of shape(3,4) with values from 0 to 11.
arr= np.arange(12).reshape(3,4)

# ->Print its shape,ndim and size.
print(arr.shape)
print(arr.ndim)
print(arr.size)

(3, 4)
2
12


In [3]:
#Q-3: Convert a 1D array of size 12 into:
arr=np.arange(12)

#->shape(3,4)
print(arr.reshape(3,4))

#->shape(2,2,3)
print(arr.reshape(2,2,3))

#->shape(6,2)
print(arr.reshape(6,2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [4]:
#Q-4: Use -1 in reshape to automatically calculate the missing dimension. Example reshape(3,4) into (2,-1)

print(arr.reshape(2,-1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [9]:
#Q-5: Create a 2D array of shape (3,3) and:
arr=np.random.randint(1,10,size=(3,3))
print(arr)

#->Flatten it into 1D using flatten()
print(arr.flatten())

#->Convert it into 1D using ravel() and change one element.
raveled=arr.ravel()
raveled[0]=100
print(raveled)

#->Check whether original array changes or not.
print(arr)

[[1 3 8]
 [7 6 6]
 [8 5 8]]
[1 3 8 7 6 6 8 5 8]
[100   3   8   7   6   6   8   5   8]
[[100   3   8]
 [  7   6   6]
 [  8   5   8]]


In [10]:
#Q-6 Take a 1D array [1,2,3,4]
arr=np.array([1,2,3,4]) 

#->Convert it into shape(1,4) using np.newaxis
arr_reshaped = arr[np.newaxis, :]
print(arr_reshaped)

#->Convert it into shape(4,1) using np.expand_dims
arr_expanded = np.expand_dims(arr, axis=1)
print(arr_expanded)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [11]:
#Q-7: Create an array of shape(1,5,1) and remove all extra dimensions using squeeze().
arr=np.array([[[1],[2],[3],[4],[5]]])
print(arr)
arr_squeezed=np.squeeze(arr)
print(arr_squeezed)

[[[1]
  [2]
  [3]
  [4]
  [5]]]
[1 2 3 4 5]


In [12]:
#Q-8: Make a 2D array of shape(2,3) and print its transpose.
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.T)

#->Verify shape before and after transpose.
print("Original shape:", arr.shape)
print("Transposed shape:", arr.T.shape)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
Original shape: (2, 3)
Transposed shape: (3, 2)


In [13]:
#Q-9: Create a 3D array of shape (2,3,4) and use transpose() to swap axes.
arr=np.random.randint(1,10,size=(2,3,4))
print("Original array shape:", arr.shape)

#->Try arr.transpose(1,0,2) and check new shape.
arr_transposed = arr.transpose(1,0,2)
print("Transposed array shape:", arr_transposed.shape)

Original array shape: (2, 3, 4)
Transposed array shape: (3, 2, 4)


In [14]:
#Q-11:You have a dataset with 1000 rows (samples) and 10 features->shape(1000,10).


#(a) Find its ndim,size and shape.
arr=np.random.rand(1000,10)
print(arr.ndim)
print(arr.size)
print(arr.shape)

#(b) Reshape it into (10,1000) and observe the diffrence.
arr_reshaped = arr.reshape(10,1000)
print(arr_reshaped.shape)

#(c) Extract a single feature as a 1D vector (1000,).
feature_1d = arr[:, 0]  # Extract the first feature
print(feature_1d.shape)

#(d) Extract a single feature as a column vector (1000,1).
feature_column = arr[:, 0:1]  # Extract the first feature as a column vector
print(feature_column.shape)

2
10000
(1000, 10)
(10, 1000)
(1000,)
(1000, 1)


In [17]:
#Q-14:A dataset has shape(10000,20) (10,000 samples,20 features).
arr=np.random.rand(10000,20)

#(a)Reshape it into (100,100,20)->100 batches,each with 100 samples.
arr_batches = arr.reshape(100, 100, 20)
print(arr_batches.shape)

#(b)Select one batch(100,20) and transpose it into (20,100).
batch = arr_batches[0]  
batch_transposed = batch.transpose(1, 0)
print(batch_transposed.shape)

(100, 100, 20)
(20, 100)


In [ ]:
#Q-15:You have daily sensor data with shape(365,24)->365 days 24 hourly readings each day.

arr=np.random.rand(365,24)

#(a)Flatten it into (8760,).
arr_flattened = arr.flatten()
print(arr_flattened.shape)

#(b)Add an extra dimension to make (365,24,1) for ML input.
arr_3d = arr.reshape(365, 24, 1)
print(arr_3d.shape)

#(c)Use sequeeze to bring it back to (365,24).
arr_squeezed = arr_3d.squeeze()
print(arr_squeezed.shape)


(8760,)
(365, 24, 1)
(365, 24)


In [21]:
#Q-16: You have stock prices with shape(30,5)->30 days, 5 companies.

arr=np.random.rand(30,5)

#(a)Extract one company's stock price as a 1D array(30,).
print(arr[0, :])

#(b)Convert the same into a column vector (30,1).
arr_column = arr[:, 0].reshape(-1, 1)
print(arr_column.shape)

#(c)Transpose the dataset to (5,30)->stocks*days.
arr_transposed = arr.T
print(arr_transposed.shape)

[0.10894627 0.33165574 0.98102007 0.07617613 0.87614264]
(30, 1)
(5, 30)


In [22]:
#Q-18:You have 200 senetences,each represented by 50 words,each word embedding of 100 dimensions.
arr=np.random.rand(200,50,100)
#->shape(200,50,100)

#(a)Flatten each sentence into (200,5000) for a bag-of-word style model.
arr_flattened = arr.reshape(200, -1)
print(arr_flattened.shape)

#(b)Transpose it to (200,100,50) so embeddings come before word positions.
arr_transposed = arr.transpose(0, 2, 1)
print(arr_transposed.shape)

#(c)Extract one sentence and reshape into (50,100)again.
sentence = arr[0]
sentence_reshaped = sentence.reshape(50, 100)
print(sentence_reshaped.shape)

(200, 5000)
(200, 100, 50)
(50, 100)


# Tasks

In [23]:
#🔹 TASK SET 1: Shape & Reshape
#Task 1

#Create a 1D NumPy array of numbers 1 to 12 and:
arr=np.arange(1,13)

#Print its shape
print(arr.shape)

#Reshape it into (3,4)
arr_reshaped = arr.reshape(3, 4)

#Print the new shape
print(arr_reshaped.shape)

(12,)
(3, 4)


In [24]:
#Task 2

#Create a 2D array of shape (2,6) and:
arr=np.arange(12).reshape(2,6)

#Convert it into a 1D array using reshape(-1)
arr_1d = arr.reshape(-1)

#Print both arrays
print("Original array:")
print(arr)
print("1D array:")
print(arr_1d)

Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
#Task 3

#Create this array:

arr=np.array([[10, 20, 30],
              [40, 50, 60]])


#Convert it into 1D using ravel()
arr_raveled = arr.ravel()

#Convert it into 1D using flatten()
arr_flattened = arr.flatten()

#Print both results
print("Raveled array:")
print(arr_raveled)
print("Flattened array:")
print(arr_flattened)

Raveled array:
[10 20 30 40 50 60]
Flattened array:
[10 20 30 40 50 60]


In [28]:
#Task 4

#Change the first value of the ravel output and observe:
arr_raveled[0] = 999

#Does the original array change or not?
print("Original array after modifying raveled array:")
print(arr)

Original array after modifying raveled array:
[[999  20  30]
 [ 40  50  60]]


In [29]:
#Task 5

#Create a NumPy array from 1 to 6 and:
arr=np.arange(1,7)

#Resize it to (2,3)
arr = arr.reshape(2,3)

#Print the array
print(arr)


[[1 2 3]
 [4 5 6]]


In [31]:
#Task 7

#Create a float array:

float_arr = np.array([2.9, 4.1, 6.8, 9.5])

#Convert it to integer using astype(int)
int_arr = float_arr.astype(int)

#Print both arrays
print("Float array:")
print(float_arr)
print("Integer array:")
print(int_arr)





Float array:
[2.9 4.1 6.8 9.5]
Integer array:
[2 4 6 9]


In [32]:
#Task 8

#Create an array with dtype='int' directly from float values and print it.
arr=np.array([2.9, 4.1, 6.8, 9.5], dtype=int)
print(arr)

[2 4 6 9]


In [33]:
#Task 9

#Create a 3D array of shape (2,2,3) using np.arange() and:
arr=np.arange(12).reshape(2,2,3)

#Print the full array
print(arr)

#Print only the first block
print(arr[0])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[0 1 2]
 [3 4 5]]


In [34]:
#Task 10

#Using nested for-loops, print each element of the 3D array.
arr=np.arange(12).reshape(2,2,3)
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        for k in range(arr.shape[2]):
            print(arr[i, j, k])

0
1
2
3
4
5
6
7
8
9
10
11


In [35]:
#Task 11

#Using np.nditer():

#Print all elements of a 3D array in one line

print("Elements of the 3D array in one line:")
for element in np.nditer(arr):
    print(element, end=' ')
#Count total elements manually
total_elements = 0
for element in np.nditer(arr):
    total_elements += 1
print(f"\nTotal elements: {total_elements}")

Elements of the 3D array in one line:
0 1 2 3 4 5 6 7 8 9 10 11 
Total elements: 12


In [36]:
#Task 12

#Using np.ndenumerate():


#Print index and value like this:

print("Index and value of each element:")
for index, value in np.ndenumerate(arr):
    print(f"Index: {index} Value: {value}")
#Index: (0, 1, 2) Value: 5

Index and value of each element:
Index: (0, 0, 0) Value: 0
Index: (0, 0, 1) Value: 1
Index: (0, 0, 2) Value: 2
Index: (0, 1, 0) Value: 3
Index: (0, 1, 1) Value: 4
Index: (0, 1, 2) Value: 5
Index: (1, 0, 0) Value: 6
Index: (1, 0, 1) Value: 7
Index: (1, 0, 2) Value: 8
Index: (1, 1, 0) Value: 9
Index: (1, 1, 1) Value: 10
Index: (1, 1, 2) Value: 11


In [37]:
#Task 13 (Thinking Task ⭐)

#From a 3D array:

#Print only elements greater than 5
arr=np.arange(12).reshape(2,2,3)
print("Elements greater than 5:")
for index, value in np.ndenumerate(arr):
    if value > 5:
        print(f"Index: {index} Value: {value}")
# Also print their index positions

Elements greater than 5:
Index: (1, 0, 0) Value: 6
Index: (1, 0, 1) Value: 7
Index: (1, 0, 2) Value: 8
Index: (1, 1, 0) Value: 9
Index: (1, 1, 1) Value: 10
Index: (1, 1, 2) Value: 11


In [38]:
#Task 14

#Create a 3D array (2,3,4) and:
arr=np.arange(24).reshape(2,3,4)

#Convert it into 1D
arr_1d=arr.reshape(-1)

#Convert it into 2D (4,6)
arr_2d=arr.reshape(4,6)

#Print shape at each step
print(f"Original shape: {arr.shape}")
print(f"1D shape: {arr_1d.shape}")
print(f"2D shape: {arr_2d.shape}")

Original shape: (2, 3, 4)
1D shape: (24,)
2D shape: (4, 6)
