# Slicing in Numpy

----------------------------------------------------------------------------------------------------------


Practice Questions:-


<!-- Basic Indexing 1D-->

Q-1: Create an array [10,20,30,40,50,60,70,80,90].

->Get the first element.

->Get the last element.

->Get the 4th element.

->Get elements at positions [0,3,5].


Q-2: Reverse the above array.

Q-3: Replace the 2nd and 3rd elements with [999,888].



<!-- Basic Indexing 2D -->

arr=[[11,12,13],
      [21,22,23],
      [31,32,33],
      [41,42,43]]


Q-4:Get element in 2nd row, 3rd column.

Q-5:Get element in last row, last column.

Q-6:Get the first column only.

Q-7:Get the last row only.

Q-8:Replace the value at position (1,1) with 999.




<!-- Slicing 1D -->


Q-9:From [5,10,15,20,25,30,35,40]:

->Extract [10,15,20].

->Extract [5,15,25,35].

->Extract every second element.

->Extract elements from index 2 till end.



<!-- Slicing 2D -->

arr=[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]


Q-10:Extract first 2 rows and first 2 columns.

Q-11:Extract last 2 rows and last 2 columns.

Q-12:Extract the middle 2*2 submatrix (,7,10,11).

Q-13:Extract all rows but only the 3rd column.

Q-14:Extract all columns but only the 2nd row.

Q-15:Reverse the order of rows.

Q-16:Reverse the order of columns.




<!-- Boolean Indexing -->

Q-17:From [10,15,20,25,30,35,40]:

->Extract all values greater than 20.

->Extract even numbers.

->Extract numbers divisible by 5 but less than 30.


Q-18:Replace all odd numbers with -1 in [1,2,3,4,5,6,7,8,9].

Q-19:From a 2D array,extract all values greater than 10.




<!-- Fancy Indexing -->

Q-20:Given [100,200,300,400,500,600], pick elements at position [0,2,4].

Q-21:From the 2D array:

[[1,2,3],
[4,5,6],
[7,8,9]]

->Extract (0,1) and (2,2).

->Extract elements at row indices [0,2] and col indices [0,1].


Q-22:Shuflle the rows of the above 2D array using fancy indexing.




<!-- Real Dataset Style Questions -->


Q-23:You have student scores array:

scores=np.array([56,72,89,45,68,91,77])

->Extract students who scored more than 70.

->Extract students who failed(<50).

->Replace all scores below 50 with 0.


Q-24:You have temperature data(celecius) for a week:

temps=np.array([32,35,30,29,40,38,31])

->Get temperatures of weekdays only(first 5).

->Get weekend temps(last 2).

->Get days where temp>35.


Q-25:You have sales data of 4 products across 5 days:

sales=np.array([
    [12,15,20,22,18],
    [14,18,24,20,25],
    [10,12,15,18,22],
    [20,22,19,24,30]
])

->Extract sales of product 1 for all days.

->Extract sales of day 3 for all products.

->Extract sales of first 2 products for first 3 days.

->Find all sales<20.

->Replace all sales<15 with 0.


Q-26:You have dataset of customers ages:

ages=np.array([15,22,35,42,60,18,25,55])

->Extract all customers older than 30.

->Extract customers between 18 and 25.

->Replace all ages above 50 with 50.


Q-27:You have marks of students in 3 subjects:


marks=np.array([
    [80,70,90],
    [60,75,85],
    [95,88,92],
    [40,65,70]
])

->Extract marks of subject 2 for all students.

->Extract marks of student 3 across all subjects.

->Extract students who scored > 80 in subject 1.

->Extract students whose average marks>75.






<!-- Where this is used in real data -->

1.Feature selection->choosing specific columns from dataset(arr[:,[1,3]]).

2.Filtering rows->selecting only rows with certain conditipon(arr[arr[:,2]>50]).

3.Capping values->Replacing outliers with thresold(arr[arr<100]=100).

4.Splitting train/test data->indexing with slicing (arr[:80] for train, arr[80:] for test).

5.Reversing sequences->time-series reversal(arr[::-1]).

6.Picking specific samples->fancy indexing with random slices (arr[[2,5,7]])


----------------------------------------------------------------------------------------------------------

In [1]:
#Q-1: Create an array [10,20,30,40,50,60,70,80,90].

#->Get the first element.

#->Get the last element.

#->Get the 4th element.

#->Get elements at positions [0,3,5].

import numpy as np

arr=np.array([10,20,30,40,50,60,70,80,90])
print(arr[0]) #first element
print(arr[-1]) #last element
print(arr[3]) #4th element
print(arr[[0,3,5]]) #elements at positions [0,3,5]


#Q-2: Reverse the above array.
print(arr[::-1])


#Q-3: Replace the 2nd and 3rd elements with [999,888].
arr[1:3]=[999,888]

10
90
40
[10 40 60]
[90 80 70 60 50 40 30 20 10]


In [ ]:
arr =np.array([[11,12,13],
       [21,22,23],
       [31,32,33],
       [41,42,43]])

# Q-4:Get element in 2nd row, 3rd column.
print(arr[1,2])

# Q-5:Get element in last row, last column.
print(arr[-1,-1])

# Q-6:Get the first column only.
print(arr[:,0])

# Q-7:Get the last row only.
print(arr[-1])

# Q-8:Replace the value at position (1,1) with 999.
arr[1,1] = 999

print(arr)

23
43
[11, 21, 31, 41]
[41, 42, 43]
[[11, 12, 13], [21, 999, 23], [31, 32, 33], [41, 42, 43]]


In [12]:
#Q-9:From [5,10,15,20,25,30,35,40]:

arr=np.array([5,10,15,20,25,30,35,40])

#->Extract [10,15,20].
print(arr[1:4])

#->Extract [5,15,25,35].
print(arr[0:8:2])

#->Extract every second element.
print(arr[::2])

#->Extract elements from index 2 till end.
print(arr[2:])

[10 15 20]
[ 5 15 25 35]
[ 5 15 25 35]
[15 20 25 30 35 40]


In [4]:
import numpy as np

arr = np.array([[1,  2,  3,  4],
                [5,  6,  7,  8],
                [9,  10, 11, 12],
                [13, 14, 15, 16]])

# Q-10: First 2 rows and first 2 columns
print("Q10:\n", arr[0:2, 0:2])

# Q-11: Last 2 rows and last 2 columns
print("Q11:\n", arr[2:4, 2:4])

# Q-12: Middle 2x2 submatrix (6,7,10,11)
print("Q12:\n", arr[1:3, 1:3])

# Q-13: All rows, only the 3rd column
print("Q13:\n", arr[:, 2])

# Q-14: All columns, only the 2nd row
print("Q14:\n", arr[1, :])

# Q-15: Reverse the order of rows
print("Q15:\n", arr[::-1, :])

# Q-16: Reverse the order of columns
print("Q16:\n", arr[:, ::-1])

Q10:
 [[1 2]
 [5 6]]
Q11:
 [[11 12]
 [15 16]]
Q12:
 [[ 6  7]
 [10 11]]
Q13:
 [ 3  7 11 15]
Q14:
 [5 6 7 8]
Q15:
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Q16:
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [5]:
#<!-- Boolean Indexing -->

#Q-17:From [10,15,20,25,30,35,40]:

arr=np.array([10,15,20,25,30,35,40])

#->Extract all values greater than 20.
print(arr[arr>20])


#->Extract even numbers.
print(arr[arr%2==0])


#->Extract numbers divisible by 5 but less than 30.
print(arr[(arr%5==0) & (arr<30)])


#Q-18:Replace all odd numbers with -1 in [1,2,3,4,5,6,7,8,9].
arr2=np.array([1,2,3,4,5,6,7,8,9])
arr2[arr2%2==1] = -1
print(arr2)

#Q-19:From a 2D array,extract all values greater than 10.
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr3[arr3>10])


[25 30 35 40]
[10 20 30 40]
[10 15 20 25]
[-1  2 -1  4 -1  6 -1  8 -1]
[11 12 13 14 15]


In [6]:
#<!-- Fancy Indexing -->

#Q-20:Given [100,200,300,400,500,600], pick elements at position [0,2,4].
arr=np.array([100,200,300,400,500,600])
print(arr[[0,2,4]])


#Q-21:From the 2D array:
arr2=np.array([['A','B','C'],['D','E','F'],['G','H','I']])

#->Extract (0,1) and (2,2).
print(arr2[[0,2],[1,2]])


# ->Extract elements at row indices [0,2] and col indices [0,1].
print(arr2[0:3:2, 0:2])

#Q-22:Shuflle the rows of the above 2D array using fancy indexing.
shuffled_arr = arr2[[2, 0, 1], :]
print(shuffled_arr)


[100 300 500]
['B' 'I']
[['A' 'B']
 ['G' 'H']]
[['G' 'H' 'I']
 ['A' 'B' 'C']
 ['D' 'E' 'F']]


In [7]:
#<!-- Real Dataset Style Questions -->


#Q-23:You have student scores array:

scores=np.array([56,72,89,45,68,91,77])

#->Extract students who scored more than 70.
print(scores[scores>70])

#->Extract students who failed(<50).
print(scores[scores<50])

#->Replace all scores below 50 with 0.
scores[scores<50] = 0
print(scores)

[72 89 91 77]
[45]
[56 72 89  0 68 91 77]


In [8]:
#Q-24:You have temperature data(celecius) for a week:

temps=np.array([32,35,30,29,40,38,31])

#->Get temperatures of weekdays only(first 5).
print(temps[0:5])

#->Get weekend temps(last 2).
print(temps[5:7])

#->Get days where temp>35.
print(temps[temps>35])

[32 35 30 29 40]
[38 31]
[40 38]


In [9]:
#Q-25:You have sales data of 4 products across 5 days:

sales=np.array([
    [12,15,20,22,18],
    [14,18,24,20,25],
    [10,12,15,18,22],
    [20,22,19,24,30]
])

#->Extract sales of product 1 for all days.
print(sales[0,:])

#->Extract sales of day 3 for all products.
print(sales[:,2])

#->Extract sales of first 2 products for first 3 days.
print(sales[0:2,0:3])

#->Find all sales<20.
print(sales[sales<20])

#->Replace all sales<15 with 0.
sales[sales<15] = 0
print(sales)

[12 15 20 22 18]
[20 24 15 19]
[[12 15 20]
 [14 18 24]]
[12 15 18 14 18 10 12 15 18 19]
[[ 0 15 20 22 18]
 [ 0 18 24 20 25]
 [ 0  0 15 18 22]
 [20 22 19 24 30]]


In [10]:
#Q-26:You have dataset of customers ages:

ages=np.array([15,22,35,42,60,18,25,55])

#->Extract all customers older than 30.
print(ages[ages>30])

#->Extract customers between 18 and 25.
print(ages[(ages>=18) & (ages<=25)])

#->Replace all ages above 50 with 50.
ages[ages>50] = 50
print(ages)

[35 42 60 55]
[22 18 25]
[15 22 35 42 50 18 25 50]


In [11]:
#Q-27:You have marks of students in 3 subjects:


marks=np.array([
    [80,70,90],
    [60,75,85],
    [95,88,92],
    [40,65,70]
])

#->Extract marks of subject 2 for all students.
print(marks[:,1])

#->Extract marks of student 3 across all subjects.
print(marks[2,:])

#->Extract students who scored > 80 in subject 1.
print(marks[marks[:,0]>80])

#->Extract students whose average marks>75.
print(marks[marks.mean(axis=1)>75])

[70 75 88 65]
[95 88 92]
[[95 88 92]]
[[80 70 90]
 [95 88 92]]
