# Iterating in Numpy

# Practical Questions

Q-1: Create a 1D NumPy array of numbers 0-9.

->Iterate using a normal for loop and print each element.

->Then multiply each element by 2 using a loop, not vectorized.


Q-2: Create a 2D array of shape(3,4) with values 0-11.

->Print each rows separately.

->Print all elements using nested loops.

->Flatten the array and iterate as a 1D array.


Q-3: Create a (2,3) array with values 10-15.

->Iterate over all elements using np.nditer.

->Modify the array in-place so that each element become its square.




Q-4: Given Two arrays:

a=np.array([1,2,3])
b=np.array([[10],[20],[30]])

->Use np.nditer([a,b]) to print their sum element wise.

->Check how broadcasting works.


Q-5: Create a 2D array of shape(3,3) with values 1-9.

->Use np.ndenumerate to print index and value of each element.

->Replace all elements at even row indices with 0.


Q-6: Create a (2,2,3) array using np.arange(12).

->Iterate block by block(normal loops).

->Iterate element by element using np.nditer.

->Use np.ndenumerate to print(i,j,k) index with its value.



In [1]:
#Q-1: Create a 1D NumPy array of numbers 0-9.
import numpy as np

arr=np.arange(0,10)
print(arr)

#->Iterate using a normal for loop and print each element.
for i in arr:
    print(i)
print('\n')

#->Then multiply each element by 2 using a loop, not vectorized.
for i in arr:
    i=i*2
    print(i)
    

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


0
2
4
6
8
10
12
14
16
18


In [2]:
#Q-2: Create a 2D array of shape(3,4) with values 0-11.
arr=np.arange(0,12).reshape(3,4)
print(arr)

#->Print each rows separately.
for i in arr:
    print(i)

print('\n')
    
#->Print all elements using nested loops.
for i in arr:
    for j in i:
        print(j)

print('\n')
#->Flatten the array and iterate as a 1D array.
for i in arr.flatten():
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


0
1
2
3
4
5
6
7
8
9
10
11


0
1
2
3
4
5
6
7
8
9
10
11


In [3]:
#Q-3: Create a (2,3) array with values 10-15.
arr=np.arange(10,16).reshape(2,3)
print(arr)

#->Iterate over all elements using np.nditer.
for x in np.nditer(arr):
    print(x)


#->Modify the array in-place so that each element become its square.
for x in np.nditer(arr,op_flags=['readwrite']):
    x[...] = x**2
print(arr)

[[10 11 12]
 [13 14 15]]
10
11
12
13
14
15
[[100 121 144]
 [169 196 225]]


In [4]:
#Q-4: Given Two arrays:

a=np.array([1,2,3])
b=np.array([[10],[20],[30]])

#->Use np.nditer([a,b]) to print their sum element wise.
for x,y in np.nditer([a,b]):
    print(x+y)

#->Check how broadcasting works.
for x,y in np.nditer([a,b]):
    print(x,'+',y,'=',x+y)

11
12
13
21
22
23
31
32
33
1 + 10 = 11
2 + 10 = 12
3 + 10 = 13
1 + 20 = 21
2 + 20 = 22
3 + 20 = 23
1 + 30 = 31
2 + 30 = 32
3 + 30 = 33


In [5]:
#Q-5: Create a 2D array of shape(3,3) with values 1-9.
arr=np.arange(1,10).reshape(3,3)

#->Use np.ndenumerate to print index and value of each element.
for index,value in np.ndenumerate(arr):
    print(index,value)

#->Replace all elements at even row indices with 0.
for index,value in np.ndenumerate(arr):
    if index[0]%2==0:
        arr[index]=0
print(arr)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9
[[0 0 0]
 [4 5 6]
 [0 0 0]]


In [6]:
#Q-6: Create a (2,2,3) array using np.arange(12).
arr=np.arange(12).reshape(2,2,3)
print(arr)

#->Iterate block by block(normal loops).
for i in arr:
    for j in i:
        for k in j:
            print(k)

#->Iterate element by element using np.nditer.
for x in np.nditer(arr):
    print(x)

#->Use np.ndenumerate to print(i,j,k) index with its value.
for index,value in np.ndenumerate(arr):
    print(index,value)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
(0, 0, 0) 0
(0, 0, 1) 1
(0, 0, 2) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 1, 2) 5
(1, 0, 0) 6
(1, 0, 1) 7
(1, 0, 2) 8
(1, 1, 0) 9
(1, 1, 1) 10
(1, 1, 2) 11
