# Searching and sorting in numpy

## Practice Questions


Q1:

Array of numbers:

arr = np.array([50, 20, 30, 10, 40])

Sort the array in ascending order using np.sort().

Sort the array in descending order.





Q2:

Array of marks:

marks = np.array([55, 70, 40, 90, 65])

Sort the marks in-place using sort() method.





Q3:

2D array of scores:

scores = np.array([[50, 20, 30],
                   [10, 60, 40]])

Sort each row.

Sort each column.





Q4:

Array with duplicate values:

arr = np.array([50, 20, 50, 10, 40])

Sort the array using mergesort to maintain stability.




🔹 Part 2: Real Dataset Style Sorting Questions

Dataset 1 — Students Marks

names = np.array(["Alice", "Bob", "Charlie", "David", "Eva"])
marks = np.array([50, 20, 30, 10, 40])

Q5:

Sort marks in ascending order.

Sort names according to marks using argsort().


Q6:

Sort only students who scored >20, both marks and names.





Dataset 2 — Employee Salaries

employees = np.array(["John", "Sara", "Mike", "Anna", "David"])
salaries = np.array([45000, 35000, 50000, 30000, 40000])

Q7:

Sort salaries in ascending order.

Sort employees according to salaries using argsort().


Q8:

Find employees earning more than 40000, sort them ascendingly, and print both names and salaries.




Dataset 3 — Product Prices

products = np.array(["Laptop", "Phone", "Tablet", "Monitor", "Keyboard"])
prices = np.array([75000, 35000, 45000, 15000, 5000])

Q9:

Sort prices in ascending order.

Sort products according to prices using argsort().


Q10:

Sort only products costing more than 20000, both names and prices.





Dataset 4 — City Temperatures (°C)

cities = np.array(["Delhi", "Mumbai", "Kolkata", "Chennai", "Bangalore"])
temps = np.array([40, 35, 38, 37, 30])

Q11:

Sort temps ascending.

Sort cities according to temperatures using argsort().


Q12:

Find cities with temperature > 35°C and sort them ascendingly by temperature.





Dataset 5 — Daily Sales (Units)

days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri"])
sales = np.array([200, 450, 300, 500, 150])

Q13:

Sort sales in ascending order.

Sort days according to sales using argsort().


Q14:

Find days where sales > 250, and sort them ascendingly by sales.

In [2]:
#Q1:
import numpy as np
#Array of numbers:

arr = np.array([50, 20, 30, 10, 40])

#Sort the array in ascending order using np.sort().
sorted_arr = np.sort(arr)
print("Sorted array in ascending order:", sorted_arr)

#Sort the array in descending order.
sorted_arr_desc = np.sort(arr)[::-1]
print("Sorted array in descending order:", sorted_arr_desc)



Sorted array in ascending order: [10 20 30 40 50]
Sorted array in descending order: [50 40 30 20 10]


In [4]:
#Q2:

#Array of marks:

marks = np.array([55, 70, 40, 90, 65])

#Sort the marks in-place using sort() method.
marks.sort()
print("Marks sorted in-place:", marks)


Marks sorted in-place: [40 55 65 70 90]


In [5]:
#Q3:

#2D array of scores:

scores = np.array([[50, 20, 30],
                   [10, 60, 40]])

#Sort each row.
sorted_rows = np.sort(scores, axis=1)
print("Scores sorted by rows:\n", sorted_rows)

#Sort each column.
sorted_cols = np.sort(scores, axis=0)
print("Scores sorted by columns:\n", sorted_cols)

Scores sorted by rows:
 [[20 30 50]
 [10 40 60]]
Scores sorted by columns:
 [[10 20 30]
 [50 60 40]]


In [6]:
#Q4:

#Array with duplicate values:

arr = np.array([50, 20, 50, 10, 40])

#Sort the array using mergesort to maintain stability.
sorted_arr_stable = np.sort(arr, kind='mergesort')
print("Sorted array with stability (mergesort):", sorted_arr_stable)

Sorted array with stability (mergesort): [10 20 40 50 50]


In [8]:
#🔹 Part 2: Real Dataset Style Sorting Questions

#Dataset 1 — Students Marks

names = np.array(["Alice", "Bob", "Charlie", "David", "Eva"])
marks = np.array([50, 20, 30, 10, 40])

#Q5:

#Sort marks in ascending order.
sorted_marks=np.sort(marks)
print("Sorted marks:", sorted_marks)

#Sort names according to marks using argsort().
sorted_indices=np.argsort(marks)
sorted_names=names[sorted_indices]
print("Names sorted according to marks:", sorted_names)

Sorted marks: [10 20 30 40 50]
Names sorted according to marks: ['David' 'Bob' 'Charlie' 'Eva' 'Alice']


In [10]:
#Q6:

#Sort only students who scored >20, both marks and names.

mask=marks > 20
filtered_marks=marks[mask]
filtered_names=names[mask]

index=np.argsort(filtered_marks)
sorted_marks=filtered_marks[index]
sorted_names=filtered_names[index]
print("Sorted marks >20:", sorted_marks)
print("Names sorted according to marks >20:", sorted_names)

Sorted marks >20: [30 40 50]
Names sorted according to marks >20: ['Charlie' 'Eva' 'Alice']


In [11]:
#Dataset 2 — Employee Salaries

employees = np.array(["John", "Sara", "Mike", "Anna", "David"])
salaries = np.array([45000, 35000, 50000, 30000, 40000])

#Q7:

#Sort salaries in ascending order.
sorted_salaries=np.sort(salaries)
print("Sorted salaries:", sorted_salaries)

#Sort employees according to salaries using argsort().
index=np.argsort(salaries)
sorted_employees=employees[index]
print("Employees sorted according to salaries:", sorted_employees)


Sorted salaries: [30000 35000 40000 45000 50000]
Employees sorted according to salaries: ['Anna' 'Sara' 'David' 'John' 'Mike']


In [13]:
# Filter salaries > 40000
mask = salaries > 40000

filtered_employees = employees[mask]
filtered_salaries = salaries[mask]

# Sort filtered salaries
index = np.argsort(filtered_salaries)

sorted_employees = filtered_employees[index]
sorted_salaries = filtered_salaries[index]

print("Employees:", sorted_employees)
print("Salaries:", sorted_salaries)

Employees: ['John' 'Mike']
Salaries: [45000 50000]


In [14]:
#Dataset 3 — Product Prices

products = np.array(["Laptop", "Phone", "Tablet", "Monitor", "Keyboard"])
prices = np.array([75000, 35000, 45000, 15000, 5000])

#Q9:

#Sort prices in ascending order.
print("Sorted prices:", np.sort(prices))

#Sort products according to prices using argsort().
index=np.argsort(prices)
sorted_products=products[index]
print("Products sorted according to prices:", sorted_products)

Sorted prices: [ 5000 15000 35000 45000 75000]
Products sorted according to prices: ['Keyboard' 'Monitor' 'Phone' 'Tablet' 'Laptop']


In [15]:
#Q10:

#Sort only products costing more than 20000, both names and prices.
mask = prices > 20000
filtered_products = products[mask]
filtered_prices = prices[mask]

index = np.argsort(filtered_prices)
sorted_products = filtered_products[index]
sorted_prices = filtered_prices[index]
print("Products costing more than 20000 sorted by price:", sorted_products)
print("Prices of products costing more than 20000 sorted:", sorted_prices)

Products costing more than 20000 sorted by price: ['Phone' 'Tablet' 'Laptop']
Prices of products costing more than 20000 sorted: [35000 45000 75000]


In [16]:
#Dataset 4 — City Temperatures (°C)

cities = np.array(["Delhi", "Mumbai", "Kolkata", "Chennai", "Bangalore"])
temps = np.array([40, 35, 38, 37, 30])

#Q11:

#Sort temps ascending.
print("Temperatures sorted in ascending order:", np.sort(temps))

#Sort cities according to temperatures using argsort().
index = np.argsort(temps)
sorted_cities = cities[index]
print("Cities sorted according to temperatures:", sorted_cities)

#Q12:

#Find cities with temperature > 35°C and sort them ascendingly by temperature.
mask = temps > 35
filtered_cities = cities[mask]
filtered_temps = temps[mask]
index = np.argsort(filtered_temps)
sorted_filtered_cities = filtered_cities[index]
sorted_filtered_temps = filtered_temps[index]
print("Cities with temperature > 35°C sorted by temperature:", sorted_filtered_cities)
print("Temperatures of cities with temperature > 35°C sorted:", sorted_filtered_temps)


Temperatures sorted in ascending order: [30 35 37 38 40]
Cities sorted according to temperatures: ['Bangalore' 'Mumbai' 'Chennai' 'Kolkata' 'Delhi']
Cities with temperature > 35°C sorted by temperature: ['Chennai' 'Kolkata' 'Delhi']
Temperatures of cities with temperature > 35°C sorted: [37 38 40]


In [17]:
#Dataset 5 — Daily Sales (Units)

days = np.array(["Mon", "Tue", "Wed", "Thu", "Fri"])
sales = np.array([200, 450, 300, 500, 150])

#Q13:

#Sort sales in ascending order.
print("Sales sorted in ascending order:", np.sort(sales))

#Sort days according to sales using argsort().
index = np.argsort(sales)
sorted_days = days[index]
print("Days sorted according to sales:", sorted_days)


#Q14:

#Find days where sales > 250, and sort them ascendingly by sales.
mask = sales > 250
filtered_days = days[mask]
filtered_sales = sales[mask]
index = np.argsort(filtered_sales)
sorted_filtered_days = filtered_days[index]
sorted_filtered_sales = filtered_sales[index]
print("Days with sales > 250 sorted by sales:", sorted_filtered_days)
print("Sales of days with sales > 250 sorted:", sorted_filtered_sales)

Sales sorted in ascending order: [150 200 300 450 500]
Days sorted according to sales: ['Fri' 'Mon' 'Wed' 'Tue' 'Thu']
Days with sales > 250 sorted by sales: ['Wed' 'Tue' 'Thu']
Sales of days with sales > 250 sorted: [300 450 500]
