# Numpy Random functions

Practice Questions


Q1.

Generate an array of 5 random float numbers between 0 and 1 using np.random.rand().




Q2.

Create a 2D random array (shape = 3x4) with random numbers between 0 and 1.




Q3.

Generate 10 random integers between 50 and 100 using np.random.randint().




Q4.

Create a 3x3 matrix of random integers between 1 and 9.




Q5.

Generate 5 random numbers from a normal distribution using np.random.randn().




Q6.

Use np.random.choice() to select 3 random elements from the array:

arr = np.array([10, 20, 30, 40, 50])




Q7.

Use np.random.choice() to pick 5 elements with replacement from:

arr = np.array([1, 2, 3, 4, 5])




Q8.

Shuffle this array using np.random.shuffle():

arr = np.array([1, 2, 3, 4, 5])




Q9.

Generate two random arrays using the same np.random.seed(10) —
check if both give the same result.




Q10.

Generate a 4x4 matrix of random integers between 10 and 99 and find:

Maximum value

Minimum value

Mean







Q11. Student Marks Simulation 

Simulate marks (0–100) of 15 students using np.random.randint()

Find the top 5 marks (sorted descending).

Randomly select 3 students for a prize.





Q12. Daily Sales Data 

Generate daily sales for 7 days between 200 and 1000 units.

Find the day with the highest sales.

Randomly pick 2 days for a special offer.

Shuffle the sales data.





Q13. Employee Salary Data 

Create salary data for 8 employees between 30,000 and 80,000.

Find the employee with the lowest salary.

Randomly pick 2 employees for a bonus.





Q14. Product Prices 

You have 10 products. Generate random prices between ₹100 and ₹1000.

Sort the prices in ascending order.

Pick 3 random products for a discount.





Q15. Weather Temperature Data 

Simulate 10 random daily temperatures between 25°C and 45°C.

Find 3 hottest days using argsort().

Randomly shuffle the temperature data.





Q16. Exam Simulation 

You are simulating marks of 1000 students (0–100).

Find the average mark.

Find how many scored above 80.

Randomly select 10 for interview.





Q17. Random Sampling in Population 

Create an array representing 1000 people IDs (1–1000).

Randomly select 50 people for a survey (no repetition).

Randomly select 5 people for a prize (with repetition).





Q18. Game Simulation 

A dice game is played 10 times.

Simulate the results using np.random.randint(1, 7, 10).

Find how many times 6 appeared.

In [2]:
#Q1.

#Generate an array of 5 random float numbers between 0 and 1 using np.random.rand().
import numpy as np
arr=np.random.rand(5)
print(arr)

[0.90535751 0.62251948 0.07602072 0.12206818 0.70586524]


In [3]:
#

#Create a 2D random array (shape = 3x4) with random numbers between 0 and 1.
arr=np.random.rand(3,4)
print(arr)

[[0.85818675 0.63039332 0.04420792 0.74630335]
 [0.06630366 0.03133835 0.10032645 0.79059455]
 [0.59264367 0.29097219 0.91383666 0.25092521]]


In [4]:
#Q3.

#Generate 10 random integers between 50 and 100 using np.random.randint().
arr=np.random.randint(50,100,10)
print(arr)

[55 65 87 68 84 51 86 99 98 67]


In [5]:
#Q4.

#Create a 3x3 matrix of random integers between 1 and 9.
arr=np.random.randint(1,9,size=(3,3))
print(arr)

[[6 4 7]
 [6 5 5]
 [3 6 8]]


In [6]:
#Q5.

#Generate 5 random numbers from a normal distribution using np.random.randn().
arr=np.random.randn(5)
print(arr)

[-0.86622659 -0.19628858  0.43495736  0.43251737  0.83022888]


In [7]:
#Q6.

#Use np.random.choice() to select 3 random elements from the array:

arr = np.array([10, 20, 30, 40, 50])
choice=np.random.choice(arr,3)
print(choice)

[30 40 40]


In [9]:
#Q7.

#Use np.random.choice() to pick 5 elements with replacement from:

arr = np.array([1, 2, 3, 4, 5])
choice = np.random.choice(arr,5,replace=True)
print(choice)


[5 4 3 4 3]


In [10]:
#Q8.

#Shuffle this array using np.random.shuffle():

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[2 3 5 1 4]


In [11]:
#Q9.

#Generate two random arrays using the same np.random.seed(10) —
#check if both give the same result.
np.random.seed(10)
arr1=np.random.rand(5)

np.random.seed(10)
arr2=np.random.rand(5)

print(arr1)
print(arr2)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]


In [12]:
#Q10.

#Generate a 4x4 matrix of random integers between 10 and 99 and find:
arr=np.random.randint(10,99,size=(4,4))
print(arr)

#Maximum value
print("Maximum value:",np.max(arr))

#Minimum value
print("Minimum value:",np.min(arr))

#Mean
print("Mean:",np.mean(arr))


[[39 18 83 10]
 [50 46 26 21]
 [64 98 72 43]
 [82 88 59 61]]
Maximum value: 98
Minimum value: 10
Mean: 53.75


In [13]:
#Q11. Student Marks Simulation 

#Simulate marks (0–100) of 15 students using np.random.randint()
marks = np.random.randint(0, 101, size=15)
print("Marks of 15 students:", marks)

#Find the top 5 marks (sorted descending).
print("Top 5 marks:", np.sort(marks)[-5:][::-1])

#Randomly select 3 students for a prize.
selected_students = np.random.choice(15, 3, replace=False)
print("Selected students (indices):", selected_students)

Marks of 15 students: [54 77 69 13 25 13 92 86 30 30 89 12 65 31 57]
Top 5 marks: [92 89 86 77 69]
Selected students (indices): [13 14 10]


In [15]:
#Generate daily sales for 7 days between 200 and 1000 units.

sales = np.random.randint(200, 1001, size=7)
print("Daily sales for 7 days:", sales)

#Find the day with the highest sales.
print("Day with highest sales (index):", np.argmax(sales))
print("Highest sales value:", np.max(sales))

#Randomly pick 2 days for a special offer.
print("Randomly picked days for special offer (indices):", np.random.choice(7, 2, replace=False))


#Shuffle the sales data.
np.random.shuffle(sales)
print("Shuffled sales data:", sales)


Daily sales for 7 days: [382 490 560 983 661 855 334]
Day with highest sales (index): 3
Highest sales value: 983
Randomly picked days for special offer (indices): [1 3]
Shuffled sales data: [983 560 855 334 490 382 661]


In [ ]:
#Q13. Employee Salary Data 

#Create salary data for 8 employees between 30,000 and 80,000.
arr = np.random.randint(30000, 80001, size=8)
print("Employee salaries:", arr)

#Find the employee with the lowest salary.
print("Lowest salary:", np.min(arr))

#Randomly pick 2 employees for a bonus.
bonus_employees = np.random.choice(8, 2, replace=False)
print("Employees selected for bonus (indices):", bonus_employees)



Employee salaries: [33626 49181 52841 67611 60632 58633 77817 54229]
Lowest salary: 33626
Employees selected for bonus (indices): [1 5]


In [17]:
#Q14. Product Prices 

#You have 10 products. Generate random prices between ₹100 and ₹1000.

prices = np.random.randint(100, 1001, size=10)
print("Product prices:", prices)

#Sort the prices in ascending order.
sorted_prices = np.sort(prices)
print("Sorted prices:", sorted_prices)

#Pick 3 random products for a discount.
discount_products = np.random.choice(10, 3, replace=False)
print("Products selected for discount (indices):", discount_products)


Product prices: [626 151 179 343 885 790 153 466 334 885]
Sorted prices: [151 153 179 334 343 466 626 790 885 885]
Products selected for discount (indices): [5 3 4]


In [18]:
#Q15. Weather Temperature Data 

#Simulate 10 random daily temperatures between 25°C and 45°C.
temperatures = np.random.randint(25, 46, size=10)
print("Daily temperatures:", temperatures)

#Find 3 hottest days using argsort().
hottest_days = np.sort(temperatures)[-3:]
print("Hottest days:", hottest_days)

#Randomly shuffle the temperature data.
np.random.shuffle(temperatures)
print("Shuffled temperatures:", temperatures)

Daily temperatures: [42 42 41 25 30 34 25 45 31 25]
Hottest days: [42 42 45]
Shuffled temperatures: [42 42 34 30 25 45 31 25 25 41]


In [19]:
#Q16. Exam Simulation 

#You are simulating marks of 1000 students (0–100).
arr = np.random.randint(0, 101, size=1000)
print("Marks of 1000 students:", arr)

#Find the average mark.
print("Average mark:", np.mean(arr))

#Find how many scored above 80.
above_80 = np.sum(arr > 80)
print("Number of students who scored above 80:", above_80)

#Randomly select 10 for interview.
interviewees = np.random.choice(1000, 10, replace=False)
print("Students selected for interview (indices):", interviewees)


Marks of 1000 students: [ 48  93  75  86  37  11  21  33  95  43  88  96  73  40  43  90  71   8
  85  72  28  30  89  25  78  81  85  62  13  41  33   4  87  94  28  39
  91   9   7  22  32   3   9  52  76  68  30  70  74  30   9   2  65  13
  75  52   5  93  84  48  62  42  34  40  46  32  94  86  58  69  45  18
  50  44   1  63  77  18  27  83  37  71  88  15  55   6  44   9  50   0
  44  68  14   4   6  42  73  44 100  90  38  20   9  40  16  75  39  58
  81  39  49  97  11  78  79  21  69  48  60  58  13   3  31  76  87  17
  29  69  50  51  20   5  70  61  16  74   4  22  19  85  73  35  35  11
  41  54  82  19  41  81  61  10  36   0  30  62  85  32  81  13  67  31
  32  96  38  37  79  59  20  31  89   0  96  25  63  59   2  30  17  59
  70  63  86  29  71  92  19   0   7  93  42  87  57  80   2  34  58  76
  10  79  32  69  91  16   5  63  83  75  42  38  57   7  88  96  38  48
  27  64  49  90   9  27  52  90  57  48  23  25  19  48  97  76  75  93
  30  31  28  79  84  21  8

In [20]:
#Q17. Random Sampling in Population 

#Create an array representing 1000 people IDs (1–1000).
arr = np.arange(1, 1001)
# print("People IDs:", arr)

#Randomly select 50 people for a survey (no repetition).
survey_participants = np.random.choice(arr, 50, replace=False)
print("Survey participants (IDs):", survey_participants)

#Randomly select 5 people for a prize (with repetition).
prize_winners = np.random.choice(arr, 5, replace=True)
print("Prize winners (IDs):", prize_winners)

Survey participants (IDs): [325 277 495 782 574 871 764 844 213 760 305 417 846 515 589 139 475 618
 733 993 396 736 577 551 882 753 715 650 538  30 186 807 323 540 679 831
 628 855 149 541 639  26 635 281 848 211 858 757 558 615]
Prize winners (IDs): [870 837 187 699 933]


In [21]:
#Q18. Game Simulation 

#A dice game is played 10 times.
game_results = np.random.randint(1, 7, 10)
print("Dice game results:", game_results)

#Simulate the results using np.random.randint(1, 7, 10).

#Find how many times 6 appeared.
six_count = np.sum(game_results == 6)
print("Number of times 6 appeared:", six_count)

Dice game results: [5 6 1 3 5 6 4 6 1 1]
Number of times 6 appeared: 3
